# Generated by Django 3.2.6 on 2022-01-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsapp', '0005_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='Landmark',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='contact_name',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='contact_number',
            field=models.CharField(default='0000', max_length=10),
            preserve_default=False,
        ),
    ]
