# Generated by Django 3.2.6 on 2022-01-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsapp', '0006_auto_20220110_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
