# Generated by Django 3.2.6 on 2021-10-14 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountsapp', '0001_initial'),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chef_profile', to='accountsapp.userprofile'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
