# Generated by Django 3.2.6 on 2022-01-09 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20211014_0612'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chef',
        ),
    ]
