# Generated by Django 3.2.6 on 2022-01-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20220118_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
