# Generated by Django 3.2.6 on 2022-01-19 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_alter_foodcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0),
        ),
        migrations.CreateModel(
            name='PaymentMethodSupported',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_on_pickup', models.BooleanField(default=False)),
                ('cash_on_delivery', models.BooleanField(default=False)),
                ('chef', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment_methods', to='food.chef')),
            ],
        ),
    ]
